name: Release

on:
  push:
    tags:
      - v*

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - name: Dependencies
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 7
          run_install: true
      - name: Generate
        run: |
          pnpm build
          pnpm package
      - uses: actions/upload-artifact@v2
        with:
          name: package deb
          path: dist/*.deb
      - uses: actions/upload-artifact@v2
        with:
          name: package AppImage
          path: dist/*.AppImage
      - uses: actions/upload-artifact@v2
        with:
          name: package tar.gz
          path: dist/*.tar.gz
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - name: Dependencies
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 7
          run_install: true
      - name: Generate
        run: |
          pnpm build
          pnpm package
      - uses: actions/upload-artifact@v2
        with:
          name: package exe
          path: dist/*.exe
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - name: Dependencies
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 7
          run_install: true
      - name: Generate
        run: |
          pnpm build
          pnpm package
      - uses: actions/upload-artifact@v2
        with:
          name: package dmg
          path: dist/*.dmg
